In [ ]:
import pandas as pd
df=pd.read_csv('dataclean.csv')
df

,AIRLINE,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,DIVERTED,AIR_TIME,DISTANCE,DAY,MONTH,YEAR
0,United Air Lines,FLL,EWR,11:55,11:51,-4,19,12:10,14:43,4,15:01,14:47,-14,0.0,153.0,1065,9,1,2019
1,Delta Air Lines,MSP,SEA,21:20,21:14,-6,9,21:23,22:32,38,23:15,23:10,-5,0.0,189.0,1399,19,11,2022
2,United Air Lines,DEN,MSP,09:54,10:00,6,20,10:20,12:47,5,12:52,12:52,0,0.0,87.0,680,22,7,2022
3,Delta Air Lines,MSP,SFO,16:09,16:08,-1,27,16:35,18:44,9,18:29,18:53,24,0.0,249.0,1589,6,3,2023
4,Spirit Air Lines,MCO,DFW,18:40,18:38,-2,15,18:53,20:26,14,20:41,20:40,-1,0.0,153.0,985,23,2,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2913797,American Airlines,JAX,CLT,17:42,17:40,-2,10,17:50,18:45,6,19:07,18:51,-16,0.0,55.0,328,13,11,2022
2913798,American Airlines,ORD,AUS,13:00,12:54,-6,10,13:04,15:14,5,15:56,15:19,-37,0.0,130.0,977,2,11,2022
2913799,Delta Air Lines,HSV,ATL,05:34,06:15,41,16,06:31,07:59,6,07:29,08:05,36,0.0,28.0,151,11,9,2022
2913800,Republic Airline,BOS,LGA,16:00,15:55,-5,19,16:14,17:04,8,17:28,17:12,-16,0.0,50.0,184,13,11,2019
2913801,Southwest Airlines,LGB,SJC,07:30,07:27,-3,9,07:36,08:28,2,08:40,08:30,-10,0.0,52.0,324,15,6,2019

In [ ]:
import pandas as pd
import numpy as np

# Fonction de conversion sécurisée
def time_to_minutes(time_str):
    """
    Convertit un string 'HH:MM' en minutes depuis minuit.
    Gère les valeurs manquantes et les formats invalides.
    """
    if pd.isna(time_str):
        return np.nan  # Conserve les NaN
    try:
        hours, minutes = map(int, str(time_str).split(':'))
        return hours * 60 + minutes
    except (ValueError, AttributeError):
        return np.nan  # En cas de format invalide (ex: "12.30" au lieu de "12:30")

# Liste des colonnes à convertir (à adapter selon votre dataset)
time_columns = [
    'CRS_DEP_TIME', 
    'DEP_TIME', 
    'WHEELS_OFF', 
    'WHEELS_ON', 
    'CRS_ARR_TIME', 
    'ARR_TIME'
]

# Application à toutes les colonnes
for col in time_columns:
    new_col_name = f"{col}_MIN"  # Nouveau nom de colonne
    df[new_col_name] = df[col].apply(time_to_minutes)

# Optionnel : Supprimer les colonnes originales
# df = df.drop(columns=time_columns)

# Aperçu des résultats
print(df[['CRS_DEP_TIME', 'CRS_DEP_TIME_MIN']].head())

  CRS_DEP_TIME  CRS_DEP_TIME_MIN
0        11:55               715
1        21:20              1280
2        09:54               594
3        16:09               969
4        18:40              1120

In [ ]:
# Après avoir créé les colonnes en minutes, supprimez les colonnes originales
colonnes_a_supprimer = [
    'CRS_DEP_TIME', 
    'DEP_TIME', 
    'WHEELS_OFF', 
    'WHEELS_ON', 
    'CRS_ARR_TIME', 
    'ARR_TIME'a
]

# Suppression sécurisée (vérifie si les colonnes existent)
df = df.drop(columns=[col for col in colonnes_a_supprimer if col in df.columns], errors="ignore")

# Vérification
print("Colonnes restantes :", df.columns.tolist())

Colonnes restantes : ['AIRLINE', 'ORIGIN', 'DEST', 'DEP_DELAY', 'TAXI_OUT', 'TAXI_IN', 'ARR_DELAY', 'DIVERTED', 'AIR_TIME', 'DISTANCE', 'DAY', 'MONTH', 'YEAR', 'CRS_DEP_TIME_MIN', 'DEP_TIME_MIN', 'WHEELS_OFF_MIN', 'WHEELS_ON_MIN', 'CRS_ARR_TIME_MIN', 'ARR_TIME_MIN']

In [ ]:
# Exemple pour Target Encoding
mean_delay_by_origin = df.groupby("ORIGIN")["ARR_DELAY"].mean().to_dict()
df["ORIGIN_ENCODED"] = df["ORIGIN"].map(mean_delay_by_origin)

In [ ]:
df

,AIRLINE,ORIGIN,DEST,DEP_DELAY,TAXI_OUT,TAXI_IN,ARR_DELAY,DIVERTED,AIR_TIME,DISTANCE,DAY,MONTH,YEAR,CRS_DEP_TIME_MIN,DEP_TIME_MIN,WHEELS_OFF_MIN,WHEELS_ON_MIN,CRS_ARR_TIME_MIN,ARR_TIME_MIN,ORIGIN_ENCODED
0,United Air Lines,FLL,EWR,-4,19,4,-14,0.0,153.0,1065,9,1,2019,715,711,730,883,901,887,8.739902
1,Delta Air Lines,MSP,SEA,-6,9,38,-5,0.0,189.0,1399,19,11,2022,1280,1274,1283,1352,1395,1390,-0.035339
2,United Air Lines,DEN,MSP,6,20,5,0,0.0,87.0,680,22,7,2022,594,600,620,767,772,772,7.380798
3,Delta Air Lines,MSP,SFO,-1,27,9,24,0.0,249.0,1589,6,3,2023,969,968,995,1124,1109,1133,-0.035339
4,Spirit Air Lines,MCO,DFW,-2,15,14,-1,0.0,153.0,985,23,2,2020,1120,1118,1133,1226,1241,1240,9.878134
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2913797,American Airlines,JAX,CLT,-2,10,6,-16,0.0,55.0,328,13,11,2022,1062,1060,1070,1125,1147,1131,4.274465
2913798,American Airlines,ORD,AUS,-6,10,5,-37,0.0,130.0,977,2,11,2022,780,774,784,914,956,919,6.062906
2913799,Delta Air Lines,HSV,ATL,41,16,6,36,0.0,28.0,151,11,9,2022,334,375,391,479,449,485,3.478135
2913800,Republic Airline,BOS,LGA,-5,19,8,-16,0.0,50.0,184,13,11,2019,960,955,974,1024,1048,1032,3.450535
2913801,Southwest Airlines,LGB,SJC,-3,9,2,-10,0.0,52.0,324,15,6,2019,450,447,456,508,520,510,2.211493

In [ ]:
# --------------------------------------------
# 1. Importation des bibliothèques
# --------------------------------------------
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
import matplotlib.pyplot as plt

# --------------------------------------------
# 2. Chargement des données
# --------------------------------------------
# Afficher les premières lignes pour vérification
print("Données brutes :")
print(df.head())

# --------------------------------------------
# 3. Prétraitement des données
# --------------------------------------------
# Clipper les retards négatifs à 0
df["ARR_DELAY"] = df["ARR_DELAY"].clip(lower=0)

# Encodage manuel des variables manquantes
def custom_target_encoder(df, col, target):
    if col in df.columns:
        mean = df.groupby(col)[target].mean().to_dict()
        df[f"{col}_ENCODED"] = df[col].map(mean)
        df = df.drop(columns=[col])
    return df

df = custom_target_encoder(df, "AIRLINE", "ARR_DELAY")
df = custom_target_encoder(df, "ORIGIN", "ARR_DELAY")
df = custom_target_encoder(df, "DEST", "ARR_DELAY")

# Suppression des colonnes problématiques
colonnes_a_supprimer = [
    "DEP_DELAY", "TAXI_IN", "WHEELS_OFF_MIN",
    "WHEELS_ON_MIN", "ARR_TIME_MIN", "DIVERTED"
]
df = df.drop(columns=[col for col in colonnes_a_supprimer if col in df.columns])

# Gestion des valeurs manquantes
df.fillna({
    'AIRLINE_ENCODED': df['AIRLINE_ENCODED'].mean(),
    'ORIGIN_ENCODED': df['ORIGIN_ENCODED'].mean(),
    'DEST_ENCODED': df['DEST_ENCODED'].mean()
}, inplace=True)

# --------------------------------------------
# 4. Séparation des features/cible
# ----------------------------

Données brutes :
            AIRLINE ORIGIN DEST  DEP_DELAY  TAXI_OUT  TAXI_IN  ARR_DELAY  \
0  United Air Lines    FLL  EWR         -4        19        4        -14
1   Delta Air Lines    MSP  SEA         -6         9       38         -5
2  United Air Lines    DEN  MSP          6        20        5          0
3   Delta Air Lines    MSP  SFO         -1        27        9         24
4  Spirit Air Lines    MCO  DFW         -2        15       14         -1

   DIVERTED  AIR_TIME  DISTANCE  DAY  MONTH  YEAR  CRS_DEP_TIME_MIN  \
0       0.0     153.0      1065    9      1  2019               715
1       0.0     189.0      1399   19     11  2022              1280
2       0.0      87.0       680   22      7  2022               594
3       0.0     249.0      1589    6      3  2023               969
4       0.0     153.0       985   23      2  2020              1120

   DEP_TIME_MIN  WHEELS_OFF_MIN  WHEELS_ON_MIN  CRS_ARR_TIME_MIN  \
0           711             730            883               901
1          1274            1283           1352              1395
2           600             620            767               772
3           968             995           1124              1109
4          1118            1133           1226              1241

   ARR_TIME_MIN  ORIGIN_ENCODED
0           887        8.739902
1          1390       -0.035339
2           772        7.380798
3          1133       -0.035339
4          1240        9.878134

In [ ]:
df

,TAXI_OUT,ARR_DELAY,AIR_TIME,DISTANCE,DAY,MONTH,YEAR,CRS_DEP_TIME_MIN,DEP_TIME_MIN,CRS_ARR_TIME_MIN,ORIGIN_ENCODED,AIRLINE_ENCODED,DEST_ENCODED
0,19,0,153.0,1065,9,1,2019,715,711,901,17.131353,14.498413,19.967840
1,9,0,189.0,1399,19,11,2022,1280,1274,1395,11.015623,10.716448,10.063523
2,20,0,87.0,680,22,7,2022,594,600,772,15.026435,14.498413,11.251682
3,27,24,249.0,1589,6,3,2023,969,968,1109,11.015623,10.716448,15.053964
4,15,0,153.0,985,23,2,2020,1120,1118,1241,17.414303,16.275912,16.777668
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2913797,10,0,55.0,328,13,11,2022,1062,1060,1147,13.175053,15.873683,12.341545
2913798,10,0,130.0,977,2,11,2022,780,774,956,15.317229,15.873683,12.996815
2913799,16,36,28.0,151,11,9,2022,334,375,449,13.087171,10.716448,10.553579
2913800,19,0,50.0,184,13,11,2019,960,955,1048,14.979637,11.587570,17.230838
2913801,9,0,52.0,324,15,6,2019,450,447,520,10.325326,10.951598,8.966447

In [ ]:
# --------------------------------------------
# 1. Importation des bibliothèques
# --------------------------------------------
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
import matplotlib.pyplot as plt

# --------------------------------------------
# 2. Chargement des données
# --------------------------------------------
# Afficher les premières lignes pour vérification
print("Données brutes :")
print(df.head())

# --------------------------------------------
# 3. Prétraitement des données
# --------------------------------------------
# Clipper les retards négatifs à 0
df["ARR_DELAY"] = df["ARR_DELAY"].clip(lower=0)

# Encodage manuel des variables manquantes
def custom_target_encoder(df, col, target):
    if col in df.columns:
        mean = df.groupby(col)[target].mean().to_dict()
        df[f"{col}_ENCODED"] = df[col].map(mean)
        df = df.drop(columns=[col])
    return df

df = custom_target_encoder(df, "AIRLINE", "ARR_DELAY")
df = custom_target_encoder(df, "ORIGIN", "ARR_DELAY")
df = custom_target_encoder(df, "DEST", "ARR_DELAY")

# Suppression des colonnes problématiques
colonnes_a_supprimer = [
    "DEP_DELAY", "TAXI_IN", "WHEELS_OFF_MIN",
    "WHEELS_ON_MIN", "ARR_TIME_MIN", "DIVERTED"
]
df = df.drop(columns=[col for col in colonnes_a_supprimer if col in df.columns])

# Gestion des valeurs manquantes
df.fillna({
    'AIRLINE_ENCODED': df['AIRLINE_ENCODED'].mean(),
    'ORIGIN_ENCODED': df['ORIGIN_ENCODED'].mean(),
    'DEST_ENCODED': df['DEST_ENCODED'].mean()
}, inplace=True)

# --------------------------------------------
# 4. Séparation des features/cible
# ----------------------------

Données brutes :
   TAXI_OUT  ARR_DELAY  AIR_TIME  DISTANCE  DAY  MONTH  YEAR  \
0        19          0     153.0      1065    9      1  2019
1         9          0     189.0      1399   19     11  2022
2        20          0      87.0       680   22      7  2022
3        27         24     249.0      1589    6      3  2023
4        15          0     153.0       985   23      2  2020

   CRS_DEP_TIME_MIN  DEP_TIME_MIN  CRS_ARR_TIME_MIN  ORIGIN_ENCODED  \
0               715           711               901       17.131353
1              1280          1274              1395       11.015623
2               594           600               772       15.026435
3               969           968              1109       11.015623
4              1120          1118              1241       17.414303

   AIRLINE_ENCODED  DEST_ENCODED
0        14.498413     19.967840
1        10.716448     10.063523
2        14.498413     11.251682
3        10.716448     15.053964
4        16.275912     16.777668

In [ ]:
from sklearn.cluster import KMeans

# Features pour le clustering (ex: durée du retard, saison, compagnie)
cluster_features = df[['ARR_DELAY', 'MONTH', 'AIRLINE_ENCODED', 'ORIGIN_ENCODED']]

kmeans = KMeans(n_clusters=5)  # 5 causes hypothétiques
df['INFERRED_CAUSE_CLUSTER'] = kmeans.fit_predict(cluster_features)

# Étiqueter manuellement les clusters basés sur les centroïdes
cluster_labels = {
    0: "Problème compagnie",
    1: "Météo",
    2: "Trafic aérien",
    3: "Retour au hangar",
    4: "Autre"
}
df['INFERRED_CAUSE'] = df['INFERRED_CAUSE_CLUSTER'].map(cluster_labels)

In [ ]:
df

,TAXI_OUT,ARR_DELAY,AIR_TIME,DISTANCE,DAY,MONTH,YEAR,CRS_DEP_TIME_MIN,DEP_TIME_MIN,CRS_ARR_TIME_MIN,ORIGIN_ENCODED,AIRLINE_ENCODED,DEST_ENCODED,INFERRED_CAUSE_CLUSTER,INFERRED_CAUSE
0,19,0,153.0,1065,9,1,2019,715,711,901,17.131353,14.498413,19.967840,4,Autre
1,9,0,189.0,1399,19,11,2022,1280,1274,1395,11.015623,10.716448,10.063523,4,Autre
2,20,0,87.0,680,22,7,2022,594,600,772,15.026435,14.498413,11.251682,4,Autre
3,27,24,249.0,1589,6,3,2023,969,968,1109,11.015623,10.716448,15.053964,4,Autre
4,15,0,153.0,985,23,2,2020,1120,1118,1241,17.414303,16.275912,16.777668,4,Autre
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2913797,10,0,55.0,328,13,11,2022,1062,1060,1147,13.175053,15.873683,12.341545,4,Autre
2913798,10,0,130.0,977,2,11,2022,780,774,956,15.317229,15.873683,12.996815,4,Autre
2913799,16,36,28.0,151,11,9,2022,334,375,449,13.087171,10.716448,10.553579,0,Problème compagnie
2913800,19,0,50.0,184,13,11,2019,960,955,1048,14.979637,11.587570,17.230838,4,Autre
2913801,9,0,52.0,324,15,6,2019,450,447,520,10.325326,10.951598,8.966447,4,Autre

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.multioutput import MultiOutputClassifier, MultiOutputRegressor
from xgboost import XGBClassifier, XGBRegressor

In [ ]:
df['RETARD_BINAIRE'] = (df['ARR_DELAY'] > 0).astype(int)  # Classification binaire
df['DUREE_RETARD'] = df['ARR_DELAY']  # Régression

In [ ]:
features = ['TAXI_OUT', 'AIR_TIME', 'DISTANCE', 'DAY', 'MONTH', 'YEAR',
            'CRS_DEP_TIME_MIN', 'DEP_TIME_MIN', 'CRS_ARR_TIME_MIN',
            'ORIGIN_ENCODED', 'AIRLINE_ENCODED', 'DEST_ENCODED']

In [ ]:
numeric_features = ['TAXI_OUT', 'AIR_TIME', 'DISTANCE', 'DAY', 'MONTH', 'YEAR',
                   'CRS_DEP_TIME_MIN', 'DEP_TIME_MIN', 'CRS_ARR_TIME_MIN']
encoded_features = ['ORIGIN_ENCODED', 'AIRLINE_ENCODED', 'DEST_ENCODED']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('enc', 'passthrough', encoded_features)
    ])

In [ ]:
pipeline_clf = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', XGBClassifier())
])

In [ ]:
pipeline_reg = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', XGBRegressor())
])

In [ ]:
y_class = df['RETARD_BINAIRE']
y_reg = df['DUREE_RETARD']

In [ ]:
# 2. Pipeline de prétraitement
# --------------------------------------------
numeric_features = ['TAXI_OUT', 'AIR_TIME', 'DISTANCE', 'DAY', 'MONTH', 'YEAR',
                   'CRS_DEP_TIME_MIN', 'DEP_TIME_MIN', 'CRS_ARR_TIME_MIN']
encoded_features = ['ORIGIN_ENCODED', 'AIRLINE_ENCODED', 'DEST_ENCODED']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('enc', 'passthrough', encoded_features)
    ])

# --------------------------------------------
# 3. Modèle multi-tâches
# --------------------------------------------
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', MultiOutputRegressor(XGBRegressor())),
    ('classifier', MultiOutputClassifier(XGBClassifier()))
])

# Définition des cibles
X = df[features]
y = df[['RETARD_BINAIRE', 'DUREE_RETARD', 'INFERRED_CAUSE_CLUSTER']]

In [ ]:
X_train, X_test, y_class_train, y_class_test = train_test_split(X, y_class, test_size=0.2, random_state=42)
_, _, y_reg_train, y_reg_test = train_test_split(X, y_reg, test_size=0.2, random_state=42)

In [ ]:
pipeline_clf.fit(X_train, y_class_train)
pipeline_reg.fit(X_train, y_reg_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['TAXI_OUT', 'AIR_TIME',
                                                   'DISTANCE', 'DAY', 'MONTH',
                                                   'YEAR', 'CRS_DEP_TIME_MIN',
                                                   'DEP_TIME_MIN',
                                                   'CRS_ARR_TIME_MIN']),
                                                 ('enc', 'passthrough',
                                                  ['ORIGIN_ENCODED',
                                                   'AIRLINE_ENCODED',
                                                   'DEST_ENCODED'])])),
                ('regressor',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsa...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [ ]:
y_pred_class = pipeline_clf.predict(X_test)
y_pred_reg = pipeline_reg.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, mean_squared_error

acc = accuracy_score(y_class_test, y_pred_class)
mse = mean_squared_error(y_reg_test, y_pred_reg)

print(f"Accuracy (RETARD_BINAIRE) : {acc:.2f}")
print(f"MSE (DUREE_RETARD) : {mse:.2f}")
from math import sqrt
rmse = sqrt(198.02)  # RMSE : Root Mean Squared Error
print(f"RMSE : {rmse:.2f} minutes")  # ~14.07 minutes

Accuracy (RETARD_BINAIRE) : 0.88
MSE (DUREE_RETARD) : 198.02
RMSE : 14.07 minutes

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Encoder la cause du retard
cause_encoder = LabelEncoder()
df['CAUSE_ENCODED'] = cause_encoder.fit_transform(df['INFERRED_CAUSE'])

In [ ]:
from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier

X_cause = df[df['RETARD_BINAIRE'] == 1][features]
y_cause = df[df['RETARD_BINAIRE'] == 1]['CAUSE_ENCODED']

pipeline_cause = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', XGBClassifier())
])

pipeline_cause.fit(X_cause, y_cause)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['TAXI_OUT', 'AIR_TIME',
                                                   'DISTANCE', 'DAY', 'MONTH',
                                                   'YEAR', 'CRS_DEP_TIME_MIN',
                                                   'DEP_TIME_MIN',
                                                   'CRS_ARR_TIME_MIN']),
                                                 ('enc', 'passthrough',
                                                  ['ORIGIN_ENCODED',
                                                   'AIRLINE_ENCODED',
                                                   'DEST_ENCODED'])])),
                ('classifier',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               col...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [ ]:
def predire_retard(info_vol):
    import pandas as pd

    input_df = pd.DataFrame([info_vol])

    # Prédiction du retard (0 ou 1)
    retard_binaire = pipeline_clf.predict(input_df)[0]

    if retard_binaire == 0:
        print("✅ Ce vol ne devrait pas avoir de retard.")
        return {
            'retard': False,
            'duree_estimee': 0,
            'cause_probable': None
        }

    # Prédiction de la durée du retard
    duree_retard = pipeline_reg.predict(input_df)[0]

    # Prédiction de la cause du retard
    cause_pred_encoded = pipeline_cause.predict(input_df)[0]
    cause_pred = cause_encoder.inverse_transform([cause_pred_encoded])[0]

    print("⚠️ Ce vol risque d'avoir un retard.")
    print(f"⏱️ Durée estimée : {duree_retard:.1f} minutes")
    print(f"❓ Cause probable : {cause_pred}")

    return {
        'retard': True,
        'duree_estimee': duree_retard,
        'cause_probable': cause_pred
    }

# Vol avec une grande distance et une faible durée d'air

In [ ]:
nouveau_vol_1 = {
    'TAXI_OUT': 30, 
    'AIR_TIME': 60, 
    'DISTANCE': 3000,  # Grande distance
    'DAY': 15, 
    'MONTH': 8, 
    'YEAR': 2023, 
    'CRS_DEP_TIME_MIN': 500, 
    'DEP_TIME_MIN': 510,  # Vol légèrement en retard
    'CRS_ARR_TIME_MIN': 600, 
    'ORIGIN_ENCODED': 12.3, 
    'AIRLINE_ENCODED': 9.7, 
    'DEST_ENCODED': 15.2
}

resultat_1 = predire_retard(nouveau_vol_1)

✅ Ce vol ne devrait pas avoir de retard.

 # Vol court, mais retardé au départ

In [ ]:
nouveau_vol_2 = {
    'TAXI_OUT': 10, 
    'AIR_TIME': 30, 
    'DISTANCE': 500,  # Petite distance
    'DAY': 20, 
    'MONTH': 9, 
    'YEAR': 2023, 
    'CRS_DEP_TIME_MIN': 600, 
    'DEP_TIME_MIN': 630,  # Retard important au départ
    'CRS_ARR_TIME_MIN': 650, 
    'ORIGIN_ENCODED': 13.1, 
    'AIRLINE_ENCODED': 10.3, 
    'DEST_ENCODED': 14.8
}

resultat_2 = predire_retard(nouveau_vol_2)

⚠️ Ce vol risque d'avoir un retard.
⏱️ Durée estimée : 38.3 minutes
❓ Cause probable : Autre

 # Vol avec une longue attente au sol mais rapide en vol

In [ ]:
nouveau_vol_3 = {
    'TAXI_OUT': 90, 
    'AIR_TIME': 120, 
    'DISTANCE': 4000,  # Long vol
    'DAY': 25, 
    'MONTH': 12, 
    'YEAR': 2023, 
    'CRS_DEP_TIME_MIN': 750, 
    'DEP_TIME_MIN': 840,  # Long taxi-out
    'CRS_ARR_TIME_MIN': 1020, 
    'ORIGIN_ENCODED': 11.0, 
    'AIRLINE_ENCODED': 8.5, 
    'DEST_ENCODED': 16.3
}

resultat_3 = predire_retard(nouveau_vol_3)

⚠️ Ce vol risque d'avoir un retard.
⏱️ Durée estimée : 173.5 minutes
❓ Cause probable : Retour au hangar

# Test 4 : Vol qui part à l'heure avec un petit retard prévu

In [ ]:
nouveau_vol_4 = {
    'TAXI_OUT': 15, 
    'AIR_TIME': 80, 
    'DISTANCE': 1200, 
    'DAY': 5, 
    'MONTH': 7, 
    'YEAR': 2023, 
    'CRS_DEP_TIME_MIN': 900, 
    'DEP_TIME_MIN': 905,  # Petit retard
    'CRS_ARR_TIME_MIN': 1005, 
    'ORIGIN_ENCODED': 12.0, 
    'AIRLINE_ENCODED': 9.3, 
    'DEST_ENCODED': 14.7
}

resultat_4 = predire_retard(nouveau_vol_4)

✅ Ce vol ne devrait pas avoir de retard.

Taxi-out : Temps que l'avion met pour rouler au sol avant le décollage.

Air time : Temps que l'avion passe en vol, entre le décollage et l'atterrissage.

Distance : Longueur du trajet entre l'aéroport de départ et celui d'arrivée.

CRS DEP TIME : Heure prévue de départ selon l'horaire du vol.

DEP TIME : Heure réelle à laquelle l'avion quitte l'aéroport.

CRS ARR TIME : Heure prévue d'arrivée à destination.

ARR TIME : Heure réelle d'atterrissage à destination.

Origin Encoded : Code numérique représentant l'aéroport de départ.

Airline Encoded : Code numérique représentant la compagnie aérienne.

Dest Encoded : Code numérique représentant l'aéroport de destination.

In [ ]:
import joblib

# Sauvegarde du modèle de classification
joblib.dump(pipeline_clf, 'pipeline_clf.pkl')

# Sauvegarde du modèle de régression
joblib.dump(pipeline_reg, 'pipeline_reg.pkl')

# Sauvegarde du modèle pour la cause probable
joblib.dump(pipeline_cause, 'pipeline_cause.pkl')

['pipeline_cause.pkl']